/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VersoesRouteImport } from './routes/versoes'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as KanbanDashboardRouteImport } from './routes/kanban-dashboard'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as IniciarHadronRouteImport } from './routes/iniciar-hadron'
import { Route as FrotaRouteImport } from './routes/frota'
import { Route as ChamadosRouteImport } from './routes/chamados'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as BaseDeConhecimentoRouteImport } from './routes/base-de-conhecimento'
import { Route as AtualizacoesRouteImport } from './routes/atualizacoes'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FrotaIndexRouteImport } from './routes/frota.index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as BaseDeConhecimentoIndexRouteImport } from './routes/base-de-conhecimento.index'
import { Route as KanbanBoardIdRouteImport } from './routes/kanban.$boardId'
import { Route as FrotaVehicleIdRouteImport } from './routes/frota.$vehicleId'
import { Route as ComercialContatosRouteImport } from './routes/comercial.contatos'
import { Route as ComercialAtividadesRouteImport } from './routes/comercial.atividades'
import { Route as ClientesClienteIdRouteImport } from './routes/clientes.$clienteId'
import { Route as ChamadosNovoRouteImport } from './routes/chamados.novo'
import { Route as BaseDeConhecimentoSlugRouteImport } from './routes/base-de-conhecimento.$slug'
import { Route as ComercialContatosLeadIdRouteImport } from './routes/comercial/contatos/$leadId'
import { Route as ComercialContatoLeadIdRouteImport } from './routes/comercial.contato.$leadId'
import { Route as ApiPublicTestPlacesRouteImport } from './routes/api/public/test-places'

const VersoesRoute = VersoesRouteImport.update({
  id: '/versoes',
  path: '/versoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanDashboardRoute = KanbanDashboardRouteImport.update({
  id: '/kanban-dashboard',
  path: '/kanban-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const IniciarHadronRoute = IniciarHadronRouteImport.update({
  id: '/iniciar-hadron',
  path: '/iniciar-hadron',
  getParentRoute: () => rootRouteImport,
} as any)
const FrotaRoute = FrotaRouteImport.update({
  id: '/frota',
  path: '/frota',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadosRoute = ChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseDeConhecimentoRoute = BaseDeConhecimentoRouteImport.update({
  id: '/base-de-conhecimento',
  path: '/base-de-conhecimento',
  getParentRoute: () => rootRouteImport,
} as any)
const AtualizacoesRoute = AtualizacoesRouteImport.update({
  id: '/atualizacoes',
  path: '/atualizacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrotaIndexRoute = FrotaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FrotaRoute,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseDeConhecimentoIndexRoute = BaseDeConhecimentoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BaseDeConhecimentoRoute,
} as any)
const KanbanBoardIdRoute = KanbanBoardIdRouteImport.update({
  id: '/$boardId',
  path: '/$boardId',
  getParentRoute: () => KanbanRoute,
} as any)
const FrotaVehicleIdRoute = FrotaVehicleIdRouteImport.update({
  id: '/$vehicleId',
  path: '/$vehicleId',
  getParentRoute: () => FrotaRoute,
} as any)
const ComercialContatosRoute = ComercialContatosRouteImport.update({
  id: '/comercial/contatos',
  path: '/comercial/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialAtividadesRoute = ComercialAtividadesRouteImport.update({
  id: '/comercial/atividades',
  path: '/comercial/atividades',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesClienteIdRoute = ClientesClienteIdRouteImport.update({
  id: '/clientes/$clienteId',
  path: '/clientes/$clienteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadosNovoRoute = ChamadosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => ChamadosRoute,
} as any)
const BaseDeConhecimentoSlugRoute = BaseDeConhecimentoSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BaseDeConhecimentoRoute,
} as any)
const ComercialContatosLeadIdRoute = ComercialContatosLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => ComercialContatosRoute,
} as any)
const ComercialContatoLeadIdRoute = ComercialContatoLeadIdRouteImport.update({
  id: '/comercial/contato/$leadId',
  path: '/comercial/contato/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTestPlacesRoute = ApiPublicTestPlacesRouteImport.update({
  id: '/api/public/test-places',
  path: '/api/public/test-places',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/atualizacoes': typeof AtualizacoesRoute
  '/base-de-conhecimento': typeof BaseDeConhecimentoRouteWithChildren
  '/calendario': typeof CalendarioRoute
  '/chamados': typeof ChamadosRouteWithChildren
  '/frota': typeof FrotaRouteWithChildren
  '/iniciar-hadron': typeof IniciarHadronRoute
  '/kanban': typeof KanbanRouteWithChildren
  '/kanban-dashboard': typeof KanbanDashboardRoute
  '/logs': typeof LogsRoute
  '/minha-conta': typeof MinhaContaRoute
  '/versoes': typeof VersoesRoute
  '/base-de-conhecimento/$slug': typeof BaseDeConhecimentoSlugRoute
  '/chamados/novo': typeof ChamadosNovoRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/comercial/atividades': typeof ComercialAtividadesRoute
  '/comercial/contatos': typeof ComercialContatosRouteWithChildren
  '/frota/$vehicleId': typeof FrotaVehicleIdRoute
  '/kanban/$boardId': typeof KanbanBoardIdRoute
  '/base-de-conhecimento/': typeof BaseDeConhecimentoIndexRoute
  '/clientes/': typeof ClientesIndexRoute
  '/frota/': typeof FrotaIndexRoute
  '/api/public/test-places': typeof ApiPublicTestPlacesRoute
  '/comercial/contato/$leadId': typeof ComercialContatoLeadIdRoute
  '/comercial/contatos/$leadId': typeof ComercialContatosLeadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/atualizacoes': typeof AtualizacoesRoute
  '/calendario': typeof CalendarioRoute
  '/chamados': typeof ChamadosRouteWithChildren
  '/iniciar-hadron': typeof IniciarHadronRoute
  '/kanban': typeof KanbanRouteWithChildren
  '/kanban-dashboard': typeof KanbanDashboardRoute
  '/logs': typeof LogsRoute
  '/minha-conta': typeof MinhaContaRoute
  '/versoes': typeof VersoesRoute
  '/base-de-conhecimento/$slug': typeof BaseDeConhecimentoSlugRoute
  '/chamados/novo': typeof ChamadosNovoRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/comercial/atividades': typeof ComercialAtividadesRoute
  '/comercial/contatos': typeof ComercialContatosRouteWithChildren
  '/frota/$vehicleId': typeof FrotaVehicleIdRoute
  '/kanban/$boardId': typeof KanbanBoardIdRoute
  '/base-de-conhecimento': typeof BaseDeConhecimentoIndexRoute
  '/clientes': typeof ClientesIndexRoute
  '/frota': typeof FrotaIndexRoute
  '/api/public/test-places': typeof ApiPublicTestPlacesRoute
  '/comercial/contato/$leadId': typeof ComercialContatoLeadIdRoute
  '/comercial/contatos/$leadId': typeof ComercialContatosLeadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/atualizacoes': typeof AtualizacoesRoute
  '/base-de-conhecimento': typeof BaseDeConhecimentoRouteWithChildren
  '/calendario': typeof CalendarioRoute
  '/chamados': typeof ChamadosRouteWithChildren
  '/frota': typeof FrotaRouteWithChildren
  '/iniciar-hadron': typeof IniciarHadronRoute
  '/kanban': typeof KanbanRouteWithChildren
  '/kanban-dashboard': typeof KanbanDashboardRoute
  '/logs': typeof LogsRoute
  '/minha-conta': typeof MinhaContaRoute
  '/versoes': typeof VersoesRoute
  '/base-de-conhecimento/$slug': typeof BaseDeConhecimentoSlugRoute
  '/chamados/novo': typeof ChamadosNovoRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/comercial/atividades': typeof ComercialAtividadesRoute
  '/comercial/contatos': typeof ComercialContatosRouteWithChildren
  '/frota/$vehicleId': typeof FrotaVehicleIdRoute
  '/kanban/$boardId': typeof KanbanBoardIdRoute
  '/base-de-conhecimento/': typeof BaseDeConhecimentoIndexRoute
  '/clientes/': typeof ClientesIndexRoute
  '/frota/': typeof FrotaIndexRoute
  '/api/public/test-places': typeof ApiPublicTestPlacesRoute
  '/comercial/contato/$leadId': typeof ComercialContatoLeadIdRoute
  '/comercial/contatos/$leadId': typeof ComercialContatosLeadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/atualizacoes'
    | '/base-de-conhecimento'
    | '/calendario'
    | '/chamados'
    | '/frota'
    | '/iniciar-hadron'
    | '/kanban'
    | '/kanban-dashboard'
    | '/logs'
    | '/minha-conta'
    | '/versoes'
    | '/base-de-conhecimento/$slug'
    | '/chamados/novo'
    | '/clientes/$clienteId'
    | '/comercial/atividades'
    | '/comercial/contatos'
    | '/frota/$vehicleId'
    | '/kanban/$boardId'
    | '/base-de-conhecimento/'
    | '/clientes/'
    | '/frota/'
    | '/api/public/test-places'
    | '/comercial/contato/$leadId'
    | '/comercial/contatos/$leadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/atualizacoes'
    | '/calendario'
    | '/chamados'
    | '/iniciar-hadron'
    | '/kanban'
    | '/kanban-dashboard'
    | '/logs'
    | '/minha-conta'
    | '/versoes'
    | '/base-de-conhecimento/$slug'
    | '/chamados/novo'
    | '/clientes/$clienteId'
    | '/comercial/atividades'
    | '/comercial/contatos'
    | '/frota/$vehicleId'
    | '/kanban/$boardId'
    | '/base-de-conhecimento'
    | '/clientes'
    | '/frota'
    | '/api/public/test-places'
    | '/comercial/contato/$leadId'
    | '/comercial/contatos/$leadId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/atualizacoes'
    | '/base-de-conhecimento'
    | '/calendario'
    | '/chamados'
    | '/frota'
    | '/iniciar-hadron'
    | '/kanban'
    | '/kanban-dashboard'
    | '/logs'
    | '/minha-conta'
    | '/versoes'
    | '/base-de-conhecimento/$slug'
    | '/chamados/novo'
    | '/clientes/$clienteId'
    | '/comercial/atividades'
    | '/comercial/contatos'
    | '/frota/$vehicleId'
    | '/kanban/$boardId'
    | '/base-de-conhecimento/'
    | '/clientes/'
    | '/frota/'
    | '/api/public/test-places'
    | '/comercial/contato/$leadId'
    | '/comercial/contatos/$leadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AtualizacoesRoute: typeof AtualizacoesRoute
  BaseDeConhecimentoRoute: typeof BaseDeConhecimentoRouteWithChildren
  CalendarioRoute: typeof CalendarioRoute
  ChamadosRoute: typeof ChamadosRouteWithChildren
  FrotaRoute: typeof FrotaRouteWithChildren
  IniciarHadronRoute: typeof IniciarHadronRoute
  KanbanRoute: typeof KanbanRouteWithChildren
  KanbanDashboardRoute: typeof KanbanDashboardRoute
  LogsRoute: typeof LogsRoute
  MinhaContaRoute: typeof MinhaContaRoute
  VersoesRoute: typeof VersoesRoute
  ClientesClienteIdRoute: typeof ClientesClienteIdRoute
  ComercialAtividadesRoute: typeof ComercialAtividadesRoute
  ComercialContatosRoute: typeof ComercialContatosRouteWithChildren
  ClientesIndexRoute: typeof ClientesIndexRoute
  ApiPublicTestPlacesRoute: typeof ApiPublicTestPlacesRoute
  ComercialContatoLeadIdRoute: typeof ComercialContatoLeadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/versoes': {
      id: '/versoes'
      path: '/versoes'
      fullPath: '/versoes'
      preLoaderRoute: typeof VersoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban-dashboard': {
      id: '/kanban-dashboard'
      path: '/kanban-dashboard'
      fullPath: '/kanban-dashboard'
      preLoaderRoute: typeof KanbanDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iniciar-hadron': {
      id: '/iniciar-hadron'
      path: '/iniciar-hadron'
      fullPath: '/iniciar-hadron'
      preLoaderRoute: typeof IniciarHadronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frota': {
      id: '/frota'
      path: '/frota'
      fullPath: '/frota'
      preLoaderRoute: typeof FrotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamados': {
      id: '/chamados'
      path: '/chamados'
      fullPath: '/chamados'
      preLoaderRoute: typeof ChamadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-de-conhecimento': {
      id: '/base-de-conhecimento'
      path: '/base-de-conhecimento'
      fullPath: '/base-de-conhecimento'
      preLoaderRoute: typeof BaseDeConhecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atualizacoes': {
      id: '/atualizacoes'
      path: '/atualizacoes'
      fullPath: '/atualizacoes'
      preLoaderRoute: typeof AtualizacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frota/': {
      id: '/frota/'
      path: '/'
      fullPath: '/frota/'
      preLoaderRoute: typeof FrotaIndexRouteImport
      parentRoute: typeof FrotaRoute
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-de-conhecimento/': {
      id: '/base-de-conhecimento/'
      path: '/'
      fullPath: '/base-de-conhecimento/'
      preLoaderRoute: typeof BaseDeConhecimentoIndexRouteImport
      parentRoute: typeof BaseDeConhecimentoRoute
    }
    '/kanban/$boardId': {
      id: '/kanban/$boardId'
      path: '/$boardId'
      fullPath: '/kanban/$boardId'
      preLoaderRoute: typeof KanbanBoardIdRouteImport
      parentRoute: typeof KanbanRoute
    }
    '/frota/$vehicleId': {
      id: '/frota/$vehicleId'
      path: '/$vehicleId'
      fullPath: '/frota/$vehicleId'
      preLoaderRoute: typeof FrotaVehicleIdRouteImport
      parentRoute: typeof FrotaRoute
    }
    '/comercial/contatos': {
      id: '/comercial/contatos'
      path: '/comercial/contatos'
      fullPath: '/comercial/contatos'
      preLoaderRoute: typeof ComercialContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/atividades': {
      id: '/comercial/atividades'
      path: '/comercial/atividades'
      fullPath: '/comercial/atividades'
      preLoaderRoute: typeof ComercialAtividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$clienteId': {
      id: '/clientes/$clienteId'
      path: '/clientes/$clienteId'
      fullPath: '/clientes/$clienteId'
      preLoaderRoute: typeof ClientesClienteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamados/novo': {
      id: '/chamados/novo'
      path: '/novo'
      fullPath: '/chamados/novo'
      preLoaderRoute: typeof ChamadosNovoRouteImport
      parentRoute: typeof ChamadosRoute
    }
    '/base-de-conhecimento/$slug': {
      id: '/base-de-conhecimento/$slug'
      path: '/$slug'
      fullPath: '/base-de-conhecimento/$slug'
      preLoaderRoute: typeof BaseDeConhecimentoSlugRouteImport
      parentRoute: typeof BaseDeConhecimentoRoute
    }
    '/comercial/contatos/$leadId': {
      id: '/comercial/contatos/$leadId'
      path: '/$leadId'
      fullPath: '/comercial/contatos/$leadId'
      preLoaderRoute: typeof ComercialContatosLeadIdRouteImport
      parentRoute: typeof ComercialContatosRoute
    }
    '/comercial/contato/$leadId': {
      id: '/comercial/contato/$leadId'
      path: '/comercial/contato/$leadId'
      fullPath: '/comercial/contato/$leadId'
      preLoaderRoute: typeof ComercialContatoLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/test-places': {
      id: '/api/public/test-places'
      path: '/api/public/test-places'
      fullPath: '/api/public/test-places'
      preLoaderRoute: typeof ApiPublicTestPlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BaseDeConhecimentoRouteChildren {
  BaseDeConhecimentoSlugRoute: typeof BaseDeConhecimentoSlugRoute
  BaseDeConhecimentoIndexRoute: typeof BaseDeConhecimentoIndexRoute
}

const BaseDeConhecimentoRouteChildren: BaseDeConhecimentoRouteChildren = {
  BaseDeConhecimentoSlugRoute: BaseDeConhecimentoSlugRoute,
  BaseDeConhecimentoIndexRoute: BaseDeConhecimentoIndexRoute,
}

const BaseDeConhecimentoRouteWithChildren =
  BaseDeConhecimentoRoute._addFileChildren(BaseDeConhecimentoRouteChildren)

interface ChamadosRouteChildren {
  ChamadosNovoRoute: typeof ChamadosNovoRoute
}

const ChamadosRouteChildren: ChamadosRouteChildren = {
  ChamadosNovoRoute: ChamadosNovoRoute,
}

const ChamadosRouteWithChildren = ChamadosRoute._addFileChildren(
  ChamadosRouteChildren,
)

interface FrotaRouteChildren {
  FrotaVehicleIdRoute: typeof FrotaVehicleIdRoute
  FrotaIndexRoute: typeof FrotaIndexRoute
}

const FrotaRouteChildren: FrotaRouteChildren = {
  FrotaVehicleIdRoute: FrotaVehicleIdRoute,
  FrotaIndexRoute: FrotaIndexRoute,
}

const FrotaRouteWithChildren = FrotaRoute._addFileChildren(FrotaRouteChildren)

interface KanbanRouteChildren {
  KanbanBoardIdRoute: typeof KanbanBoardIdRoute
}

const KanbanRouteChildren: KanbanRouteChildren = {
  KanbanBoardIdRoute: KanbanBoardIdRoute,
}

const KanbanRouteWithChildren =
  KanbanRoute._addFileChildren(KanbanRouteChildren)

interface ComercialContatosRouteChildren {
  ComercialContatosLeadIdRoute: typeof ComercialContatosLeadIdRoute
}

const ComercialContatosRouteChildren: ComercialContatosRouteChildren = {
  ComercialContatosLeadIdRoute: ComercialContatosLeadIdRoute,
}

const ComercialContatosRouteWithChildren =
  ComercialContatosRoute._addFileChildren(ComercialContatosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AtualizacoesRoute: AtualizacoesRoute,
  BaseDeConhecimentoRoute: BaseDeConhecimentoRouteWithChildren,
  CalendarioRoute: CalendarioRoute,
  ChamadosRoute: ChamadosRouteWithChildren,
  FrotaRoute: FrotaRouteWithChildren,
  IniciarHadronRoute: IniciarHadronRoute,
  KanbanRoute: KanbanRouteWithChildren,
  KanbanDashboardRoute: KanbanDashboardRoute,
  LogsRoute: LogsRoute,
  MinhaContaRoute: MinhaContaRoute,
  VersoesRoute: VersoesRoute,
  ClientesClienteIdRoute: ClientesClienteIdRoute,
  ComercialAtividadesRoute: ComercialAtividadesRoute,
  ComercialContatosRoute: ComercialContatosRouteWithChildren,
  ClientesIndexRoute: ClientesIndexRoute,
  ApiPublicTestPlacesRoute: ApiPublicTestPlacesRoute,
  ComercialContatoLeadIdRoute: ComercialContatoLeadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
